### ISSUE TITLE
Create gifs for setup and run in the READMEs

### ISSUE THREAD

**Issue by sertansenturk** [sertansenturk/cookiecutter-ds-docker#34]
**Reason**
It makes the project accessible and intuitive for first users

**Design**

Make sure that no personal info is being recorded => fresh browser window, in "no-distraction" mode (e.g. F11 in Firefox)

**GIF 1** 
1. run cookiecutter 
2. bake a new project with some "interesting" naming (we can discuss what it means)
3. cd to repo folder
4. run `make` and wait Jupyter URL is ready. Run with a) the images already downloaded, b) run once before so that we don't wait for db init and upgrades
5. Click the link which opens Jupyter lab in a browser 
5.1 Run mlflow example notebook
6. Open http://localhost:5000/ to connect to `mlflow` and show that the experiment is recorded
7. Save the gif under `images/`
8. Put the gif under "running a baked project" section in the `README`

**GIF 2** 
1. Cut the screencast above and start from step **4**
2. Save the gif under `{{cookiecutter: repo_slug}}/images`
3. Put it in the running the services in `{{cookiecutter: repo_slug}}/README.md`

**Acceptance Criteria**
- Reviewed and liked (:stuck_out_tongue:) by @sertansenturk 

**Outcome**
- The gifs saved to the repo and added to the README

**Comment by halil-erdogan** [comment]
Hey @sertansenturk , for the first one, what do you think about the following 

![screencast_2](https://user-images.githubusercontent.com/34948815/81505739-d36b0000-92f1-11ea-8ead-2fbee3a016d3.gif)

**Comment by sertansenturk** [comment]
I think this is really good! Well done!!

If it will be easy to record a few suggestions:

1. Can you make the repo name "Awesome Project" instead of "awesome"?
2. While entering the cookiecutter variables, can you wait 2-3 seconds between so people have time to follow
3. Please wait a few seconds after each click in the Jupyter interface.
3. No need to change the experiment name in the notebook and re-run. Let's run the notebook once and then click the mlflow URL in the notebook.
4. Please wait a few seconds after each click in the mlflow interface.

**Comment by halil-erdogan** [comment]
Thanks! I will follow them, thanks for the advice. 💯 I will edit based on your advices. 🌵

**Comment by halil-erdogan** [comment]
Hey, I have created new gif based on your feedback. @sertansenturk  May you review it 🏂  

**EDIT: Better version is in the next message.** :) 

![screencast_4](https://user-images.githubusercontent.com/34948815/81511958-43db4680-931d-11ea-9193-e46a61a4dc1d.gif)

**Comment by halil-erdogan** [comment]
Hey, I also changed some minor parts. 🐎 May you review this version? ![screencast_2](https://user-images.githubusercontent.com/34948815/81512374-6f136500-9320-11ea-9b66-aa9e77315971.gif)

**Comment by sertansenturk** [comment]
Perfect! 

I don't think we need GIF2 for now, and let's make a few simplifications on the original design. The remaining steps are:

- [ ] Upload the gif to `docs/images/`
- [ ] Insert it to the end of *Quickstart* section in `README.md` and `docs/index.rst` ([how to insert images to rst](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/images.html)).
- [ ] Can you share the original video in here (if the size is not too big) or with me from wetransfer/dropbox etc. for documentation purposes?

Once these are finished, please open a PR to dev for me to review. Then we can merge the changes!

Thanks a lot for this amazing work!

**Comment by halil-erdogan** [comment]
Thanks a lot. 🦉 I will take care of remaining steps soon. 🦁

**Comment by halil-erdogan** [comment]
Hey @sertansenturk , I opened [PR](https://github.com/sertansenturk/cookiecutter-ds-docker/pull/47) about this. Also for the file, you can reach via attached zip file.
[gif_installation_video.zip](https://github.com/sertansenturk/cookiecutter-ds-docker/files/4640078/gif_installation_video.zip)

**Comment by halil-erdogan** [comment]
We have merged it. So maybe we can close this issue 🐎 @sertansenturk
